# Generated by Django 3.2.5 on 2021-07-24 17:50

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_newsletter_contents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor_TV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Headline', models.CharField(max_length=20)),
                ('video', embed_video.fields.EmbedVideoField()),
            ],
        ),
    ]
